他人のサイトにボタンを表示->ボタンクリック後にアラート表示させる
frouriolabs/feasy pull request #2
Opened 2024-11-02 02:53 UTC by tak42

#### 実行結果
![image](https://github.com/user-attachments/assets/4a36edf5-d8ed-43c8-8a33-6a8e80253350)

#### アラート表示までの流れ
1. `favoriteBtn.ts`を改修
2. `npm run build:favorite`を実行
3. 出力された`favoriteBtn.js`を[JSファイルホスティング用リポジトリ](https://github.com/tak42/my-js-hosting)にアップロード
4. ブックマークレットにてホスティングしたJSファイルを他サイトで実行
5. ボタンが表示されるのを確認
6. ボタンクリック後にアラート表示されるのを確認

2024-11-02 03:16 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +    btnElm.style.setProperty(key, style[key as keyof typeof style]);
`as const` 以外のasは極力使ってはならない

Object.keysが型の詳細情報を喪失するメソッドなのでKeyに意味があるときは使わない

一般には配列に連想配列を詰める

2024-11-02 03:18 UTC, solufa requested changes
修正が終わったらPRページ右上にある再レビュー依頼ボタンを押す

2024-11-04 15:18 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +    btnElm.style.setProperty(key, style[key as keyof typeof style]);
@solufa 
extendsとkeyofを併用することで、CSSStyleDeclaration型以外での変更を受け付けないようにしました。
また、それに伴い不必要な型定義を削除しました。

2024-11-04 16:28 UTC, solufa approved these changes
コメントの意図とは違うが、今はこれでもよい

2024-11-04 16:28 UTC, merged