readmeの拡充
frouriolabs/feasy pull request #4
Opened 2024-11-12 05:56 UTC by memaiiro

環境整備の説明文の追加
npm install -g npm-run-all
npm install --save-dev npm-run-all

2024-11-12 08:07 UTC, solufa requested changes
npm-run-allは要らないはずなんだけどなあ・・・

2024-11-12 09:26 UTC, solufa requested changes
再レビュー依頼するのは指摘の修正が完了したタイミング

コミットを追加しても作業が途中なら依頼しなくてよい

2024-11-12 09:30 UTC, memaiiro commented
> 再レビュー依頼するのは指摘の修正が完了したタイミング
> コミットを追加しても作業が途中なら依頼しなくてよい

慣れてなくてすいません。先ほどPR出しました。ご確認の程お願いいたします。

2024-11-12 09:31 UTC, solufa commented
Draftのままになってる

2024-11-12 10:17 UTC, memaiiro commented
> Draftのままになってる

ドラフト解除しました。ご確認の程、お願いいたします。

2024-11-12 10:18 UTC, solufa commented on README.md
>  First, run the development server:
First, という英文と合ってない

改行ルールもそろえる

2024-11-12 10:18 UTC, solufa commented on README.md
>  First, run the development server:
Getting Startedとも合ってない気がする

2024-11-12 10:19 UTC, solufa requested changes
既存の英文との相性も確認してください

2024-11-12 10:56 UTC, memaiiro commented on README.md
>  First, run the development server:
コミット「ReadMeを一部日本語に変更」で該当箇所を日本語に書き直しました。

2024-11-15 05:39 UTC, memaiiro commented
コミット「ReadMeを一部日本語に変更」で該当箇所を日本語に書き直しました。

2024-11-15 06:08 UTC, solufa requested changes
中途半端に言語を混ぜないでおくれ・・・
全体を日本語に統一すればよい

2024-11-20 05:39 UTC, memaiiro commented
> 全体を日本語に統一すればよい
かしこまりました。ありがとうございます。統一しました。

2024-11-20 06:55 UTC, solufa commented on README.md
> +`pages/api`ディクショナリは、`/api/*`と紐づけされています。 このディクショナリ内のファイルは React ページの代わりに、[API routes](https://nextjs.org/docs/api-routes/introduction) として取り扱われています。
Feasyには `pages/api`が存在しません

2024-11-20 06:56 UTC, solufa commented on README.md
> +## 更に学ぶには
Next.jsの勉強をFeasyがガイドする理由がありません

2024-11-20 06:57 UTC, solufa commented on README.md
> +## Vercel にてデプロイするには
Vercelにデプロイする予定はありません

2024-11-20 06:57 UTC, solufa requested changes
単純に日本語化するだけでなく、情報の取捨選択もしてください

2024-11-20 07:21 UTC, memaiiro commented on README.md
> +`pages/api`ディクショナリは、`/api/*`と紐づけされています。 このディクショナリ内のファイルは React ページの代わりに、[API routes](https://nextjs.org/docs/api-routes/introduction) として取り扱われています。
かしこまりました。文章削除しました。

2024-11-20 07:21 UTC, memaiiro commented on README.md
> +## 更に学ぶには
確かにガイドする必要がないため文章削除いたします。

2024-11-20 07:22 UTC, memaiiro commented on README.md
> +## Vercel にてデプロイするには
かしこまりました。文章削除いたします。

2024-11-20 07:22 UTC, memaiiro commented
> 単純に日本語化するだけでなく、情報の取捨選択もしてください
かしこまりました。修正しました。

2024-11-20 07:26 UTC, solufa approved these changes
LGTM

2024-11-20 07:27 UTC, merged