Reactで閉じるボタンを作成し押したら外のスクリプトに連絡しiframeを消す（iframeの中にlocalhostのNext.jsを表示 ）
frouriolabs/feasy pull request #6
Opened 2024-11-22 17:03 UTC by tak42

#### 1. iframeはlocalhostのNext.jsを表示する
![image](https://github.com/user-attachments/assets/e10a053e-fd98-43fc-916e-5d1e30afab28)

#### 2. localhost内の閉じるボタンを押下するとiframeが見えなくなる
![image](https://github.com/user-attachments/assets/773bae12-4483-4e5c-9edc-9c39da522f17)

#### 3. iframeを再表示させられる
![image](https://github.com/user-attachments/assets/eb6c940c-4ca2-453e-8c38-ccbe77562fb0)

2024-11-23 01:32 UTC, solufa commented on src/scripts/iframeHideBtn.tsx
> +import styles from './index.module.css';
ページコンポーネント以外のtsxはアッパーキャメルケース

2024-11-23 01:33 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +const containerId = 'iframeContainer';
埋め込み先のサイトに同じIDが存在すると破綻してしまう

2024-11-23 01:34 UTC, solufa requested changes
要修正

2024-11-23 04:28 UTC, tak42 commented on src/scripts/iframeHideBtn.tsx
> +import styles from './index.module.css';
`IframeHideBtn.tsx`に修正しました。

2024-11-23 04:29 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +const containerId = 'iframeContainer';
先頭にプレフィックスと末尾UUIDを付与するように修正しました。

2024-11-23 14:56 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +const containerId = `feasy_iframeContainer_${uuid}`;
ID経由せずにcontainerのインスタンスを直接参照すればよいのでは？

2024-11-23 14:56 UTC, solufa requested changes
要修正

2024-11-24 02:58 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +const containerId = `feasy_iframeContainer_${uuid}`;
IDを削除してインスタンスを直接参照するように修正しました。

2024-11-24 13:23 UTC, solufa approved these changes
LGTM

2024-11-24 13:23 UTC, merged