「データ共有」ボタンを押したら外側のサイトのフォームに反映させる
frouriolabs/feasy pull request #7
Opened 2024-12-02 15:14 UTC by tak42

#### 課題内容
React側に氏名など主要なフォームを3つくらい設置し「データ共有」ボタンを押したらiframeは閉じて、外側のサイトのフォームに反映させる
外側のサイトのDOM構造に依存するので公共系の大手サイトに固定するのが良いと思う
他のメンバーも同じサイトを使うことになる

#### 実行結果
1. フォーム反映前
 ![image](https://github.com/user-attachments/assets/80d2c254-a242-4768-afa6-7541c1913a91)
2. 共有情報入力
 ![image](https://github.com/user-attachments/assets/8645497c-6a94-4cc9-8e0b-be39b937447d)
3. データ共有実行
 ![image](https://github.com/user-attachments/assets/b873cd7e-8b8d-4e2d-a6fc-4a7e26fa995e)

2024-12-03 04:43 UTC, solufa commented on src/scripts/index.module.css
> +}
「css 8の倍数」で検索

2024-12-03 04:45 UTC, solufa commented on src/scripts/index.module.css
> +  margin: 0 0 0 auto;
bottomだけauto当てるが、どんな効果がある？
動作確認してないから確信はないけど、変化なさそう

2024-12-03 05:03 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +  if (event.origin !== LOCALHOST_URL) return false;
値を返す必要がない

2024-12-03 05:13 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +  actionFunc[0].func(postData.contents);
key/valが確定していて列挙表示する必要がないデータはRecord型を使って表現する

```ts
iframePostActions[postData.action](postData.contents)
```

という表現でCallできるようになる

2024-12-03 05:13 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +};
行間詰めすぎて読みづらい

2024-12-03 05:14 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +  });
filter関数内で副作用のある処理をしてはいけない

2024-12-03 05:15 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +  );
getElementByIdとかで簡易に表現できない？

2024-12-03 05:16 UTC, solufa commented on src/scripts/favoriteBtn.ts
> +}[];
配列をtype定義することはほとんどない

PostContentまで

2024-12-03 05:18 UTC, solufa commented on src/scripts/Post.type.ts
> +    | [];
空配列のUnionに意味がない

2024-12-03 05:18 UTC, solufa requested changes
要修正

2024-12-06 22:47 UTC, tak42 commented on src/scripts/index.module.css
> +}
@solufa 
全体的に８の倍数ルールで数値を指定するようにしました。

2024-12-06 22:49 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +  if (event.origin !== LOCALHOST_URL) return false;
@solufa 
`return`に修正しました。

2024-12-06 22:50 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +  actionFunc[0].func(postData.contents);
@solufa 
type定義を見直して、Record型によるCallに変更しました。

2024-12-06 22:50 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +};
@solufa 
frouriolabsの他のコードを参考に行間を修正しました。
いかがでしょうか？

2024-12-06 22:56 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +  });
@solufa 
type定義を見直して、方法としてシンプルになるように修正しました。
いかがでしょうか？

2024-12-06 22:59 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +  );
@solufa 
こちら試したのですが、getElementsByTagNameのほうがHTMLInputElement型で取得できるので制御しやすかったです。
getElementByIdではHTMLInputElement型に変換する必要があります。

2024-12-06 22:59 UTC, tak42 commented on src/scripts/favoriteBtn.ts
> +}[];
@solufa 
Type定義を全体的に修正しました。

2024-12-06 22:59 UTC, tak42 commented on src/scripts/Post.type.ts
> +    | [];
@solufa 
Type定義を全体的に修正しました。

2024-12-07 15:36 UTC, solufa approved these changes
LGTM

2024-12-07 15:36 UTC, merged